### ISSUE TITLE
Remove duplicate files.

### ISSUE THREAD

**Issue by ianshulx** [ianshulx/DSA-Hacktoberfest2022#142]

**Comment by Nimesh-21** [comment]
Can you please assign this to me?

**Comment by ianshulx** [comment]
okay, @Nimesh-21

**Comment by prakharjadaun** [comment]
Can you please assign this to me too? I am new to open source and looking forward to create my first pull request.

**Comment by ianshulx** [comment]
@prakharjadaun, Okay

**Comment by rohanmalik0** [comment]
Hello @ianshulx  Assign this task to me. It will be a great pleasure for me to do this task for you.

**Comment by ianshulx** [comment]
Sorry, @rohanmalik0 I've already assigned 2 people on this issue, but you can work on other problems, You can also find an issue in this repo and send an issue request.
