### ISSUE TITLE
How About refining README and adding "STEPS TO CONTRIBUTE"?

### ISSUE THREAD

**Issue by saubhagya-gupta** [ianshulx/DSA-Hacktoberfest2022#18]

**Comment by saubhagya-gupta** [comment]
Would you mind adding "STEPS TO CONTRIBUTE" in your repositery?

**Comment by ianshulx** [comment]
Sure @saubhagya-gupta, I am adding steps to contribute, pls don't forget to star this repo.

**Comment by saubhagya-gupta** [comment]
I have created a PR for the same here - https://github.com/ianshulx/DSA-Hacktoberfest2022/pull/20

**Comment by ianshulx** [comment]
okay thanks
