### ISSUE TITLE
Add dynamic programming algorithms and problems

### ISSUE THREAD

**Issue by ianshulx** [ianshulx/DSA-Hacktoberfest2022#30]

**Comment by BipinSah** [comment]
Please assign me this issue as I will do it properly. @ianshulx

**Comment by ianshulx** [comment]
Okay @BipinSah

**Comment by ianshulx** [comment]
Hey, @BipinSah  are you working on it?

**Comment by BipinSah** [comment]
Yes, I am @ianshulx. Can I ask how many programs should I submit?

**Comment by ianshulx** [comment]
@BipinSah, Just Create a folder, name it "dynamic programming" and add all important programs , you can check out here https://www.geeksforgeeks.org/top-algorithms-and-data-structures-for-competitive-programming/#algo2
