### ISSUE TITLE
Create Sieve of Eratosthenes Python Code?

### ISSUE THREAD

**Issue by AyushCSE04** [ianshulx/DSA-Hacktoberfest2022#37]
Can i be assigned this?

**Comment by ianshulx** [comment]
@AyushCSE04  Can you do it in C++ or C?

**Comment by AyushCSE04** [comment]
@ianshulx In Whichever Yes , I can do it in C Also

**Comment by ianshulx** [comment]
@AyushCSE04  okay do it in C or C++
