### ISSUE TITLE
Add important Data structures programs using Java.

### ISSUE THREAD

**Issue by ianshulx** [ianshulx/DSA-Hacktoberfest2022#45]
Create a new folder "Data structure using Java", and add all important programs.

**Comment by RachitGarg-12** [comment]
Hey @ianshulx   please assign me this issue.

**Comment by ianshulx** [comment]
Sure @RachitGarg-12

**Comment by RachitGarg-12** [comment]
@ianshulx why did you delete my comment and unassign in both issues?

**Comment by ianshulx** [comment]
Sorry for that, I see your profile and you haven't forked this repo so I thought You are not working on this, If you are working, please tell me.

**Comment by Anubhakri13** [comment]
hey @ianshulx, May you assign this to me?

**Comment by ianshulx** [comment]
okay @Anubhakri13, work on it.

**Comment by ianshulx** [comment]
okay, @gs16062021  but don't add duplicate programs.

**Comment by prakharjadaun** [comment]
Hey @ianshulx I can also contribute to this issue. And will ensure that I do not add any duplicate or copied file. Can you assign this to me?

**Comment by ianshulx** [comment]
Sure @prakharjadaun, work on it.

**Comment by rahulr2109** [comment]
Hey @ianshulx  can you assign this task to me .
i really want to contribute to this issue
