### ISSUE TITLE
Add all important algorithms using java.

### ISSUE THREAD

**Issue by ianshulx** [ianshulx/DSA-Hacktoberfest2022#46]
Create a separate folder for different types of problems like Sorting algorithms using Java, Graph algo using java, dynamic programming using Java, etc, and add all important programs.

**Comment by RachitGarg-12** [comment]
Hey @ianshulx  please assign me this issue.

**Comment by ianshulx** [comment]
Okay @RachitGarg-12

**Comment by ianshulx** [comment]
okay @Hussain6,  you can work on it, just create a separate folder "Sorting algorithm using java " and contribute your files.

**Comment by Ashpreet-Singh** [comment]
Hey @ianshulx can you assign me this card

**Comment by ianshulx** [comment]
Okay @Ashpreet-Singh,

**Comment by ianshulx** [comment]
Okay @RachitGarg-12 I've merged all PRs

**Comment by nhimanshujain** [comment]
Hi @ianshulx , can you please assign this issue to me. I am going to add a few important algorithms in JAVA

**Comment by Umang3072** [comment]
Can you please assign this to me , I would like to add some important sorting algorithms.

**Comment by nhimanshujain** [comment]
Hi @ianshulx Please merge issue #162 after review
